### ISSUE TITLE
Doesn't work in Glyphs 3 when applied as a Filter argument?

### ISSUE THREAD

**Issue by elenage** [guidoferreyra/Obfuscator#5]
It doesn't work, Glyphs doesn't specify what exactly went wrong. Says "Error applying Obfuscator"

**Comment by guidoferreyra** [comment]
Hi, I cant reproduce this error.
What version number of Glyphs 3 do you have? Are you using the last version of this plugin?

Best

**Comment by elenage** [comment]
It is 3.0.3 3066. I'm using the latest version that Glyphs offers. Perhaps I'm using a wrong syntax? 
Here is what I have: in the Filter field (After the "Filter"):
"Obfuscator; char:.notdef; include:zero, one, two, three, four, five, six, seven, eight, nine;"
<img width="771" alt="Screenshot 2021-03-02 at 21 38 39" src="https://user-images.githubusercontent.com/20543172/109719032-f841a400-7b9f-11eb-9259-7396a21cb96a.png">

**Comment by guidoferreyra** [comment]
I updated Glyphs to that version and used your setting and it works. Do you get something on the console (aka Macro Panel)?

**Comment by elenage** [comment]
Nope, not a single line. I tried to apply it in an empty file (all letters are empty) and replacing a couple of numbers but it gives me the same error. Here is the [file ](https://www.dropbox.com/s/nd9obhx90rdoxsv/test-obfuscator2.glyphs?dl=0)

**Comment by elenage** [comment]
Can this be related to the python version used?

**Comment by guidoferreyra** [comment]
Your file worked for me.
I’m quite lost with this issue, maybe @schriftgestalt can help us to debug it.

**Comment by schriftgestalt** [comment]
It works for me. Can you run scripts in the macro window?

**Comment by elenage** [comment]
Yes, I can run scripts.
Actually, if I re-launch Glyphs and am trying to export the file, it does give me some "error text". All attempts after - Glyphs only shows me what you see on the screenshot above.
Here is the text:
Traceback (most recent call last):

File "GlyphsApp/GlyphsApp/plugins.py", line 795, in processFont_withArguments_

TypeError: Need 0 arguments, got 1


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "GlyphsApp/GlyphsApp/plugins.py", line 808, in processFont_withArguments_

AttributeError: 'Obfuscator' object has no attribute 'menuName'

**Comment by schriftgestalt** [comment]
I tried it again and now the error showed up. It seems to be a rare problem with the PyObjC bridge. I circumvented it.

**Comment by elenage** [comment]
thanks, Georg! Will the plugin work after the next app update? Or the plugin needs to be updated?

**Comment by schriftgestalt** [comment]
Yes.

**Comment by elenage** [comment]
Ok, I'll do both :-D
Thanks for looking into this guys!
